### ISSUE TITLE
'Return To Parent Layer' missing from client

### ISSUE THREAD

**Issue by beekerr** [rnayabed/streampi_client#1]
Great app you've got going here! 

I was unable to navigate back to the main panel after selecting a folder. Perhaps adding a Up and Back button to folder pages by default? 

Client: Raspberry Pi 3b+
Server: Windows 10

**Comment by rnayabed** [comment]
You can swipe from left to right to return to the previous pane, or also use debug buttons from settings (ugly approach)

a dedicated back action button will be there in folder actions in the upcoming version

If you liked the work, please [donate](https://www.paypal.com/paypalme/ladiesman6969)

**Comment by MrTheoW** [comment]
Both methodes doesn't work for the Android APK I'm afraid.

**Comment by rnayabed** [comment]
@TWillemse @beekerr join [discord](https://discord.gg/BExqGmk) to test out alpha builds for Server/Client 1.0.0

**Comment by rnayabed** [comment]
fixed in 1.0
