### ISSUE TITLE
.APK doesn't install on android 

### ISSUE THREAD

**Issue by Emmanuel-Grunn** [rnayabed/streampi_client#3]

**Comment by rnayabed** [comment]
Is your device 64 bit or 32 bit

**Comment by Emmanuel-Grunn** [comment]
I've a Vodafone Smart Prime 6, 32 Bit. Android 6.0.1

-Emmanuel

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rnayabed** [comment]
sorry it wont work on 32 bit devices. it was clearly mentioned in the install instructions. We may be having a web app version of the client in the future but I cant give you an ETA for that.
