### ISSUE TITLE
Apk

### ISSUE THREAD

**Issue by ghost** [rnayabed/streampi_client#7]
Apk is not installed. This is the error message everytime i try to install the apk.

**Comment by JacoVanR** [comment]
Can somebodey f****ng respond!?!?!?!!

**Comment by rnayabed** [comment]
> Can somebodey f****ng respond!?!?!?!!

The APK for 0.0.6 is compiled on a very old version of Gluon Client, and is quite unstable. Also, if your device is a 32-bit device, it wont work. We are currently rewriting everything from the scratch, and will make an android app available for 1.0.0 very soon.

**Comment by ghost** [comment]
Okay i will wait for that then

**Comment by MrTheoW** [comment]
> Can somebodey f****ng respond!?!?!?!!

This is a free project under development by just a handful of people who actually also have a life next to this. (Think Work, School, Family and whatever they do in life)
There is no need to talk this way my friend. The developers are doing the best they can.

**Comment by rnayabed** [comment]
@JacoVanR this repository has been shifted and moved to a better place.

Stream-Pi has been re-written from scratch and is much better now than ever before. Proper android support is available as well (upto android 5.0) (64 bit device)

Server: https://github.com/stream-pi/server/releases/tag/1.0.0-EA%2B3
Client: https://github.com/stream-pi/client/releases/tag/1.0.0-EA%2B3
